name: app_restaurant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  sticky_headers: ^0.3.0+2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  avatar_stack: ^1.2.0
  image_picker: ^1.0.7
  flutter_quill: ^8.6.0
  dropdown_search: ^5.0.6
  awesome_dialog: ^3.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  excel: ^4.0.2
  path_provider: ^2.1.2
  flutter_otp_text_field: ^1.1.1
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  money_formatter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
