name: app_restaurant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  sticky_headers: ^0.3.0+2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  avatar_stack: ^1.2.0
  image_picker: ^1.0.7
  flutter_quill: ^8.1.1
  dropdown_search: ^5.0.6
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  assets:
    - assets/images/
    - assets/svg/
