name: app_restaurant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  dropdown_search: ^5.0.6
  awesome_dialog: ^3.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  path_provider: ^2.1.2
  flutter_otp_text_field: ^1.1.1
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  money_formatter: ^0.0.5
  intl: ^0.18.1
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  flutter_widget_from_html: ^0.14.11
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.67.0
  modal_bottom_sheet: ^3.0.0
  flutter_slidable: ^3.1.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconApp.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
